### ISSUE TITLE
Use Case and DFD 3.1 

### ISSUE THREAD

**Issue by brentmac94** [brentmac94/ISQA-3420-A1#11]
Please review my DFD and Use Cases and let me know what I should fix in the comments on this issue.

Thank you!

**Comment by germonprez** [comment]
The DFD is looking good. One minor issue is that the manager should be able to get the vulnerability information back too (not just the license stuff). The same would hold true for the developer --> that they get back Software Package License and Vulnerability Information 

Regarding the use case: 

You can remove the vending machine one. 

Work on your formatting. You need to get some line breaks in there. 

aable is spelled wrong

We aren't working with project level information yet (preconditions). I think that a more reasonable precondition is that the License and Vulnerability database is current and up to date. 

Check your main success scenario again

Corporate Manaager is misspelled 

For the second use case, you should include that the developer also is getting this information into the DB. 

For #2, I don't really understand the Manager providing ... statement in Stakeholders

I don't think that a precondition is 'proper project information has been provided' is a precondition for #2. Perhaps that a working version of FOSSology is running. 

Failed end condition has a trailing with...

Trigger? Developer uploads software package?
