### ISSUE TITLE
DFD Comments - Sept 15

### ISSUE THREAD

**Issue by germonprez** [brentmac94/ISQA-3420-A1#7]
Move your DFD Dictionary to its own MD file. 

Make sure your DFD Dictionary and DFD items match 100% (including case)

The return OSS Results should be Package & License Info Response 

Package & License Info Request should be the same as Request for Package & License Info (unless the data is actually transformed in some way).

**Comment by brentmac94** [comment]
Updates have been made in my repository. Please review and let me know what other changes you would like me to make and I will make them!
